dashboard/urls.py
from django.urls import path

from .views import *

app_name = 'dashboard'

urlpatterns = [path('dashboard/', dashboard, name='dashboard')]

loan/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('misc.urls')),
    path('', include('users.urls')),
    path('', include('dashboard.urls')),
    path('accounts/', include('allauth.urls')),
    path('__debug__/', include(debug_toolbar.urls)),  # for debug urls
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

misc/urls.py
from django.urls import path
from .views import *

app_name = 'misc'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('calculator/', calculator, name='calculator'),
    path('checkout_stripe', checkout_stripe, name='checkout_stripe'),
    path('stripe_checkout_session', stripe_checkout_session, name='stripe_checkout_session'),
    path('success/', success),
    path('cancelled/', cancelled),
]

templates/partials/_footer.html
 {% load static %}
 {% block extracss %}
 	<link rel="stylesheet" href="{% static 'css/footer.css' %}">
 {% endblock extracss %}
  <footer class="info_section mt-4 ">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="info_contact">
            <h5>
              <a href="" class="navbar-brand">
                <span>
                  Loan
                </span>
              </a>
            </h5>
            <p>
              <i class="fa fa-map-marker" aria-hidden="true"></i>
              Your Address
            </p>
            <p>
              <i class="fa fa-phone" aria-hidden="true"></i>
              +1234567890
            </p>
            <p>
              <i class="fa fa-envelope" aria-hidden="true"></i>
              admin@loan.com
            </p>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_info">
            <h5>
              Information
            </h5>
            <p>
              Hello World. Hi this is information about loan. This includes more information about loan.
            </p>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_links">
            <h5>
              Useful Link
            </h5>
            <ul>
              <li>
                <a href="#">
                  Home
                </a>
              </li>
              <li>
                <a href="#">
                  About
                </a>
              </li>
              <li>
                <a href="#">
                  Products
                </a>
              </li>
              <li>
                <a href="#">
                  Why Us
                </a>
              </li>
              <li>
                <a href="#">
                  Testimonial
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_form ">
            <h5>
              Newsletter
            </h5>
            <form action="">
              <input type="email" placeholder="Enter your email">
              <button>
                Subscribe
              </button>
            </form>
            <div class="social_box">
              <a href="">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-youtube" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>

templates/partials/_nav.html
 {% load static %}
 {% block extracss %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
	<link rel="stylesheet" href="{% static 'css/nav.css' %}">
 {% endblock extracss %}
<!-- nav section strats -->
    <header class="header_section mb-5">
      <div class="header_bottom">
        <div class="container-fluid">
          <nav class="navbar navbar-expand-lg custom_nav-container ">
            <a class="navbar-brand" href="{% url 'misc:index' %}" >
              <span>
                Loan
              </span>
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class=""> </span>
            </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ">
                <li class="nav-item">
                  <a href= "{% url 'misc:index' %}" class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                  <a href= "{% url 'misc:about' %}" class="nav-link"> About</a>
                </li>
                <li class="nav-item">
                  <a href= "{% url 'misc:calculator' %}" class="nav-link"> Calculator</a>
                </li>

								{% if user.is_authenticated %}
									<li class="nav-item">
										<a class="nav-link" href="{% url 'dashboard:dashboard' %}">Hi, {{user.username|slice:"10"|title}}</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
									</li>
									{% else %}
									<li class="nav-item">
										<a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="{% url 'account_login' %}">Log In</a>
									</li>
								{% endif %}
              </ul>
            </div>
          </nav>
        </div>
      </div>
    </header>
    <!-- end nav section -->