dashboard/urls.py
from django.urls import path

from .views import *

app_name = 'dashboard'

urlpatterns = [path('dashboard/', dashboard, name='dashboard')]

loan/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('misc.urls')),
    path('', include('users.urls')),
    path('', include('dashboard.urls')),
    path('accounts/', include('allauth.urls')),
    path('__debug__/', include(debug_toolbar.urls)),  # for debug urls
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('profile-details', profile_details, name='details'),
    path(
        'update_profile_details', update_profile_details, name='update_profile_details'
    ),  # this api is depreciated for now
]

users/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User

from .constants import GENDER

# These fields are added so that
# 1. Email field is shown while adding user from admin panel
# 2. Two user with same email will not be created
User._meta.get_field('email').blank = False
User._meta.get_field('email')._unique = True


class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='userprofile')
    first_name = models.CharField(max_length=200, null=True, blank=True)
    last_name = models.CharField(max_length=200, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER, default='Male')
    dob = models.DateField(blank=True, null=True)
    contact_number = models.CharField(max_length=10, null=True, blank=True)
    loan_amount = models.FloatField(blank=True, null=True)
    loan_term = models.PositiveIntegerField(default=10)
    installment_amount = models.FloatField(blank=True, null=True)
    is_complete = models.BooleanField(default=False)
    is_approved_by_admin = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_or_save_user_profile(sender, created, instance, **kwargs):
    # only create while new account is created
    if created:
        UserProfile.objects.create(user=instance)
        instance.userprofile.save()

users/forms.py
from django import forms
from .constants import GENDER

from django.forms.widgets import NumberInput

import re


def is_valid_phone_number(number):
    if len(number) < 10 or len(number) > 10:
        return False
    pattern = re.compile("9?[7-9][0-9]{9}")
    return pattern.match(number)


class UserProfileForm(forms.Form):
    first_name = forms.CharField(
        label='First Name', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Your First Name'})
    )
    last_name = forms.CharField(
        label='Last Name', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Your Last Name'})
    )
    address = forms.CharField(
        label='Address', max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Your Address'})
    )
    gender = forms.CharField(label='Gender', widget=forms.RadioSelect(choices=GENDER))
    date_of_birth = forms.DateTimeField(
        required=False, label="Date", widget=NumberInput(attrs={'type': 'date', 'id': 'dob'})
    )
    contact_number = forms.IntegerField(
        label='Contact Number', widget=forms.TextInput(attrs={'placeholder': 'Your Contact Number'})
    )
    loan_amount = forms.FloatField(
        label='Loan Amount', widget=forms.TextInput(attrs={'placeholder': 'Your Loan Amount'})
    )
    loan_term = forms.IntegerField(
        label='Loan Term in Years', widget=forms.TextInput(attrs={'placeholder': 'Your Loan Term in Years'})
    )
    installment_amount = forms.FloatField(
        label='Installment Amount',
        widget=forms.TextInput(attrs={'placeholder': 'Your Installment Amount'}),
    )

    def clean(self):
        cleaned_data = super().clean()
        contact_number_value = cleaned_data.get('contact_number')
        loan_term_value = cleaned_data.get('loan_term')
        loan_amount_value = cleaned_data.get('loan_amount')
        installment_amount_value = cleaned_data.get('installment_amount')
        is_valid_contact = is_valid_phone_number(str(contact_number_value))
        if not is_valid_contact:
            raise forms.ValidationError({'contact_number': 'Enter valid contact number'})
        if loan_amount_value < 1000000:
            raise forms.ValidationError({'loan_amount': 'Loan amount should be greater than 1 Million'})
        if loan_term_value <= 0:
            raise forms.ValidationError({'loan_term': 'Loan term cannot be zero or less'})
        elif loan_term_value > 40:
            raise forms.ValidationError({'loan_term': 'Loan term cannot be more than 40 years'})
        if installment_amount_value > loan_amount_value:
            raise forms.ValidationError(
                {'installment_amount': 'Installment amount cannot be greater than loan amount'}
            )

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.http import JsonResponse

from datetime import datetime
from django.utils import dateparse
from django.utils.dateparse import parse_date

from .models import UserProfile
from .forms import UserProfileForm


@login_required
def profile_details(request):
    if request.method == "POST":
        form = UserProfileForm(request.POST)
        if form.is_valid():
            user_profile = UserProfile.objects.get(user_id=request.user.id)
            data_to_be_updated = {
                "first_name": form.cleaned_data['first_name'],
                "last_name": form.cleaned_data['last_name'],
                "address": form.cleaned_data['address'],
                "gender": form.cleaned_data['gender'],
                "date_of_birth": form.cleaned_data['date_of_birth'],
                "contact_number": form.cleaned_data['contact_number'],
                "loan_amount": form.cleaned_data['loan_amount'],
                "loan_term": form.cleaned_data['loan_term'],
                "installment_amount": form.cleaned_data['installment_amount'],
                "is_complete": True,
            }
            for key, value in data_to_be_updated.items():
                setattr(user_profile, key, value)
            user_profile.save()
            return redirect('dashboard:dashboard')
    else:
        form = UserProfileForm(initial={'gender': 'Male'})
    return render(request, 'users/profile_details.html', {'form': form})


# This API is depreciated for now.
# Currently this API does not support proper validation
@login_required
def update_profile_details(request):
    if request.method == "POST":
        user_profile = UserProfile.objects.get(user_id=request.user.id)
        request_data = request.POST
        try:
            dob = request_data['dob']
            dob = datetime.strptime(dob, "%Y-%m-%d").date()
            print(dob)
            user_profile.first_name = request_data['firstname']
            user_profile.last_name = request_data['lastname']
            user_profile.address = request_data['address']
            user_profile.gender = request_data['gender']
            user_profile.dob = dob
            user_profile.contact_number = int(request_data['contactNumber'])
            user_profile.loan_amount = float(request_data['loanAmount'])
            user_profile.loan_term = int(request_data['loanTerm'])
            user_profile.installment_amount = float(request_data['installmentAmount'])

            user_profile.is_complete = True
            user_profile.save()
            response = {'message': 'Post received'}
        except:
            data = {'result': 'error', 'message': 'Form invalid', 'form': 'oops.'}
            return JsonResponse(data, status_code=400)
    else:
        response = {'message': 'Thank you for visiting this URL'}
    return JsonResponse(response)

templates/users/profile_details.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block extracss %}
<link rel="stylesheet" href={% static 'css/form.css' %}>
{% endblock extracss %}
 
{% block title %}Profile Details{% endblock title %}

{% block content %}
	<div class="container">
	<div class="row">
		<div class="offset-lg-2 col-lg-8 profile-detail-card">
			<div class="alert alert-dark text-center mb-4" role="alert">
				Please fill this form carefully. This data is required to activate your account. Else you cannot apply for loan.
			</div>
			<h2 class="text-center mt-3 header-text">
				Your Profile Details
			</h2>

			<form action="" method="POST">
				{% csrf_token %}
				{{ form|crispy}}
				<button class="btn btn-success" type="submit">Submit</button>
			</form>
		</div>
	</div>
	

	{% comment %} <form action="" method="POST" id="profileForm">
		{% csrf_token %}
		<input type="text" id="fname" name="firstname" placeholder="Your first name" required>
		<input type="text" id="lname" name="lastname" placeholder="Your last name" required>
		<input type="text" id="address" name="address" placeholder="Your address" required>
		<div class="form-check radio-buttons">
			<div>
				<input class="form-check-input" type="radio" name="gender" id="gridRadios1" value="Male" checked>
        <label class="form-check-label" for="gridRadios1">
          Male
        </label>
			</div>
			<div>
				<input class="form-check-input" type="radio" name="gender" id="gridRadios2" value="Female">
        <label class="form-check-label" for="gridRadios2">
          Female
        </label>
			</div>
			<div>
				<input class="form-check-input" type="radio" name="gender" id="gridRadios2" value="None">
        <label class="form-check-label" for="gridRadios2">
          None
        </label>
			</div>
				
    </div>
		<input class="input-group date py-2 px-4 mt-1 mb-1 date-picker" data-provide="datepicker" type="date" id="dob" name="dob" min="1930-01-02" required>
		<input type="number" id="contactNumber" name="contactNumber" placeholder="Your contact number" required>
		<input type="number" id="loanAmount" name="loanAmount" placeholder="Your loan amount" required>
		<input type="number" id="loanTerm" name="loanTerm" placeholder="Your loan term in years" required>
		<input type="number" id="installementAmount" name="installmentAmount" step=0.01 placeholder="Your installment amount" required>
		<button type="submit" class="btn btn-success mt-3" id="profile-save">Save</button>
	</form> {% endcomment %}
		
	</div>
{% endblock content %}

{% block extrascript %}
<script>
{% comment %} $("#profileForm").submit(function(e){
	e.preventDefault();
	$.blockUI({ message: null });
	$.ajax({
		type:'POST',
		url:"{% url 'users:update_profile_details'%}",
		data : $('#profileForm').serialize(),
		success:function(data){
			$.unblockUI();
			window.location = {% url 'dashboard:dashboard' %}
		},
		error:function(xhr, errmsg, err){
			$.unblockUI();
			console.log(errmsg);
		}
	})
}); {% endcomment %}
var today = new Date()
var today_date = today.getFullYear()+'-'+(today.getMonth()+1)+'-'+today.getDate();
document.getElementById('dob').setAttribute("min","1930-01-02");
document.getElementById('dob').setAttribute("max", today_date);
</script>
{% endblock extrascript %}